version: '3.8'

services:
  redis:
    image: beemarket-api-platform-redis
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data