version: '3.8'

services:
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_CONFIG_PATH}:/etc/postgresql/postgresql.conf
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
